stages:
- validate
- generate
- deploy

validate-data:
   stage: validate
   tags:
    - grid5000-docker
   image: debian:stretch
   script:
    - apt-get update && apt-get -y install ruby rake ruby-hashdiff
    - gem install hash_validator
    - rake valid:schema
    - rake valid:duplicates
    - rake valid:homogeneity

generate-reference-api:
   stage: generate
   tags:
    - grid5000-docker
   image: debian:stretch
   script:
    - apt-get update && apt-get -y install ruby rake ruby-hashdiff git
    - gem install hash_validator
    - export TZ=Europe/Paris
    - rake reference-api
    - git status
    - echo "Checking that git status output is empty..."
    - sh -c '[ "`git status -s`" = "" ]'
    - git diff --exit-code

deploy:
   stage: deploy
   tags:
    - grid5000-shell
   script:
    - /srv/ci-runner-scripts/bin/update-api-servers
